### ISSUE TITLE
劉正吉，您好！

### ISSUE THREAD

**Issue by xuefengedu** [lioujj/pxt-IR#3]
劉正吉，您好！
您這個擴展包做得很贊，有幾個老師需要，我翻譯成簡體中文版，跟您說下，感謝！
readme裡面有說明了您是這個擴展包的作者，感謝！
https://github.com/xuefengedu/pxt-IR-zh-cn

**Comment by xuefengedu** [comment]
just close it, thanks.

**Comment by lioujj** [comment]
OK
